POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/b6fac78a-377d-41e2-a6e6-e3bfd00e771b/attendees
Content-Type: application/json

{
  "name": "João Victor",
  "email": "joao@email.com"
}