POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/a13abf3d-537a-4e8d-83da-e955013f7126/attendees
Content-Type: application/json

{
  "name": "João Victor",
  "email": "joao@email.com"
}

###

GET http://localhost:3333/events/a13abf3d-537a-4e8d-83da-e955013f7126

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/a13abf3d-537a-4e8d-83da-e955013f7126/attendees?query=